### ISSUE TITLE
Rich text -> Link: Set rel="nofollow" and target="_blank"

### ISSUE THREAD

**Issue by leevi978** [Balve-user/garmeres_v3#154]

**Comment by mashazyu** [comment]
@leevi978 , hello!

I like the cause and would like to contribute, if this issue is still up for grabs.

**Comment by leevi978** [comment]
@mashazyu Yes! It really is! I am only one person doing this and would love any help 🙏🏼❤️

**Comment by mashazyu** [comment]
Hello @leevi978,

I have a proposal. I tried to push local branch to the repo and got the following error message

![image](https://github.com/user-attachments/assets/7221f5e8-8971-4f60-ad2f-43fd6fd10147)

I verified that I can push to my own repo. Is it possible that I should use different procedure to open pull request or I should be given a permission to do so? Could you please check from your side?

**Comment by leevi978** [comment]
Hi @mashazyu , I appreciate your time spent on this and I am looking forward to see your proposal.

Could you fork the repo and create a pull-request from your fork to this repo?
